import Head from "next/head";
import Message from "@/components/Message";
import { useEffect, useState } from "react";
import { db } from "@/utils/firebase";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Link from "next/link";

export default function Home() {
  //Create a state with all the posts that are coming in from the database
  const [allPosts, setAllPosts] = useState([]);

  const getPosts = async () => {
    const collectionRef = collection(db, "posts");

    //This shows the posts in descending order of when they were posted
    const q = query(collectionRef, orderBy("timestamp", "desc"));

    //onSnapshot which updates our data in real time, it automatically updates for us live
    const unsubscribe = onSnapshot(q, (postsSnapshot) => {
      setAllPosts(
        //This will return the array of docs(posts)
        postsSnapshot.docs.map((doc) => ({
          //For each document, we want an object returned.
          ...doc.data(),
          //Getting the posts ID from firebase.
          id: doc.id,
        }))
      );
    });
    return unsubscribe;
  };

  //on page load,
  useEffect(() => {
    console.log("This runs once! When the page renders.");
    getPosts();
  }, []);

  return (
    <>
      <Head>
        <title>Blogin App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-12 text-xl font-medium">
        <h2>See what other people are saying</h2>
        {allPosts.map((post) => (
          <Message key={post.id} {...post}>
            <Link href={{ pathname: `/${post.id}`, query: { ...post } }}>
              {/* If there are no comments, post.comments? will allow it to render */}
              <button>
                {post.comments?.length > 0 ? post.comments?.length : 0} Comments
              </button>
            </Link>
          </Message>
        ))}
      </div>
    </>
  );
}
